dist: trusty
sudo: required
language: node_js

node_js:
  - "6"
os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
after_success:
  - npm run test-coverage
  - npm run report-coverage